<a href="https://colab.research.google.com/github/ISPC-PROYECTOS/CienciaDatosABP/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importamos el dataset de Kaggle, buscamos el archivo CSV

In [1]:
import kagglehub
import os

path = kagglehub.dataset_download("lucalullo/global-ghg-gas-emissions-by-country-1950-2024")
print("Ruta del dataset:", path)

archivos = os.listdir(path)
print("Archivos descargados:", archivos)

Downloading to /root/.cache/kagglehub/datasets/lucalullo/global-ghg-gas-emissions-by-country-1950-2024/1.archive...

100%|██████████| 299k/299k [00:00<00:00, 47.4MB/s]

Extracting files...
Ruta del dataset: /root/.cache/kagglehub/datasets/lucalullo/global-ghg-gas-emissions-by-country-1950-2024/versions/1
Archivos descargados: ['emissioni-gas-serra-globali-per-paese-1950-2024.csv']

Buscamos el primer archivo que termine en .csv y unimos la ruta de la carpeta con el nombre del archivo. Luego lo cargamos en pandas y verificamos que se haya cargado.

In [2]:
import pandas as pd

# Buscamos el primer archivo que termine en '.csv'
nombre_csv = [archivo for archivo in archivos if archivo.endswith('.csv')][0]

# Unimos la ruta de la carpeta con el nombre del archivo
ruta_completa = os.path.join(path, nombre_csv)

# Lo cargamos en pandas
df = pd.read_csv(ruta_completa)

# Vemos las primeras 5 filas para confirmar que todo salió bien
df.head()

       country  year iso_code  total_ghg  ghg_per_capita
0  Afghanistan  1950      AFG  19.868742        2.555078
1  Afghanistan  1951      AFG  21.069101        2.673967
2  Afghanistan  1952      AFG  22.094320        2.766014
3  Afghanistan  1953      AFG  23.255630        2.872235
4  Afghanistan  1954      AFG  24.250988        2.954572

# **Primer análisis del dataset**
Este conjunto de datos contiene las emisiones de gases de efecto invernadero a nivel nacional desde 1950 hasta 2024.

El conjunto de datos se deriva del conjunto de datos de emisiones de CO₂ y gases de efecto invernadero publicado por Our World in Data, que integra varias fuentes científicas ampliamente utilizadas en la investigación climática.

Cada observación representa un registro de un país y un año, y abarca 199 países de todo el mundo.

Incluye información sobre:
- Emisiones totales de gases de efecto invernadero
- Emisiones de gases de efecto invernadero per cápita

**Variables**

- Country → nombre del país
- Year → año de observación
- Iso_code → Código de país ISO
- Total_ghg → emisiones totales de gases de efecto invernadero expresadas en millones de toneladas de CO₂ equivalente
- Ghg_per_capita → emisiones de gases de efecto invernadero por persona, expresadas en toneladas de CO₂ equivalente per cápita.

El dataset posee un total de 14.925 registros

**Fuentes**

- Dataset “Global GHG gas emissions by country (1950–2024)” publicado por Luca Lullo en Kaggle.
- Datos originales derivados de Our World in Data, que integran:

   - Global Carbon Project - Global Carbon Budget
   - PRIMAP-hist greenhouse gas emissions database
   - United Nations World Population Prospects
   - Gapminder population series

# **Análisis de datos inicial**
Vamos a explorar el df para entender su estructura, identificar valores nulos, duplicados y obtener estadísticas descriptivas.

In [3]:
# 1. Información general del DataFrame y tipos de datos
print('Información general del DataFrame:')
df.info()

# 2. Conteo de valores nulos por columna
print('\nConteo de valores nulos por columna:')
display(df.isnull().sum())

Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14925 entries, 0 to 14924
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         14925 non-null  object
 1   year            14925 non-null  int64
 2   iso_code        14925 non-null  object
 3   total_ghg       14475 non-null  float64
 4   ghg_per_capita  14475 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 583.1+ KB

Conteo de valores nulos por columna:

country             0
year                0
iso_code            0
total_ghg         450
ghg_per_capita    450
dtype: int64

El dataset muestra un total de 14.925 registros distribuidos en cinco columnas. Las variables categóricas y la temporal están completas, pero las métricas de emisiones (total_ghg y ghg_per_capita) presentan 450 valores faltantes cada una (un 3 % del total). Esto indica que, aunque la mayoría de este dataset es consistente, será necesario aplicar técnicas de tratamiento de datos faltantes para garantizar la validez de futuros análisis.

In [4]:
# 3. Conteo de filas duplicadas
num_duplicados = df.duplicated().sum()
print(f'Número de filas duplicadas: {num_duplicados}')

if num_duplicados > 0:
    print('\nEjemplo de filas duplicadas:')
    display(df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist()).head()) # Muestra algunas filas duplicadas

Número de filas duplicadas: 0

El análisis de duplicados muestra que el dataset no tiene filas repetidas, confirmando que son registros únicos y no será necesario aplicar técnicas de limpieza relacionadas con duplicados.

In [5]:
# 4. Parámetros estadísticos descriptivos para columnas numéricas
print('\nParámetros estadísticos descriptivos:')
display(df.describe())

Parámetros estadísticos descriptivos:

               year     total_ghg  ghg_per_capita
count  14925.000000  14475.000000    14475.000000
mean    1987.000000    188.028820        9.259861
std       21.649436    706.305423       12.160517
min     1950.000000     -9.218572       -5.197811
25%     1968.000000      7.289340        2.858160
50%     1987.000000     34.407463        5.909035
75%     2006.000000     99.218967       11.049553
max     2024.000000  14107.006836      369.705292

Las columnas numéricas muestran que la variable "year" abarca desde 1950 hasta 2024. Las variables de emisiones (total_ghg y ghg_per_capita) muestran una gran variabilidad entre países y años; estos parámetros permiten identificar tendencias centrales y la dispersión de los datos.

In [6]:
# 5. Parámetros estadísticos descriptivos para columnas categóricas (objetos)
print('\nParámetros estadísticos descriptivos para columnas categóricas:')
display(df.describe(include='object'))

Parámetros estadísticos descriptivos para columnas categóricas:

            country iso_code
count         14925    14925
unique          199      199
top     Afghanistan      AFG
freq             75       75

El dataset muestra 199 países distintos. Cada país cuenta con aproximadamente 75 registros, lo que indica la presencia de múltiples observaciones por país a lo largo del rango temporal.

# Limpieza y estandarización del dataset
Verificamos si es necesario aplicar algun método de limpieza o estandarización para poder trabajar con los datos.

In [12]:
#Quitamos los espacios iniciales y finales, y cambiamos los objetos a minúsculas
df['country'] = df['country'].str.strip().str.lower()
df['iso_code'] = df['iso_code'].str.strip().str.lower()

#Listamos los países para verificar si alguno se encuentra escrito de diferente manera
columnas_anormalizar = ["country", "iso_code"]
for columna in columnas_anormalizar:
    print("------")
    print(df[columna].value_counts(dropna=False).to_string())

------
country
afghanistan                         75
albania                             75
algeria                             75
andorra                             75
angola                              75
antigua and barbuda                 75
argentina                           75
armenia                             75
australia                           75
austria                             75
azerbaijan                          75
bahamas                             75
bahrain                             75
bangladesh                          75
barbados                            75
belarus                             75
belgium                             75
belize                              75
benin                               75
bhutan                              75
bolivia                             75
bosnia and herzegovina              75
botswana                            75
brazil                              75
brunei                              75
bulgaria                            75
burkina faso                        75
burundi                             75
cambodia                            75
cameroon                            75
canada                              75
cape verde                          75
central african republic            75
chad                                75
chile                               75
china                               75
colombia                            75
comoros                             75
congo                               75
costa rica                          75
cote d'ivoire                       75
croatia                             75
cuba                                75
cyprus                              75
czechia                             75
democratic republic of congo        75
denmark                             75
djibouti                            75
dominica                            75
dominican republic                  75
east timor                          75
ecuador                             75
egypt                               75
el salvador                         75
equatorial guinea                   75
eritrea                             75
estonia                             75
eswatini                            75
ethiopia                            75
fiji                                75
finland                             75
france                              75
gabon                               75
gambia                              75
georgia                             75
germany                             75
ghana                               75
greece                              75
grenada                             75
guatemala                           75
guinea                              75
guinea-bissau                       75
guyana                              75
haiti                               75
honduras                            75
hong kong                           75
hungary                             75
iceland                             75
india                               75
indonesia                           75
iran                                75
iraq                                75
ireland                             75
israel                              75
italy                               75
jamaica                             75
japan                               75
jordan                              75
kazakhstan                          75
kenya                               75
kiribati                            75
kosovo                              75
kuwait                              75
kyrgyzstan                          75
laos                                75
latvia                              75
lebanon                             75
lesotho                             75
liberia                             75
libya                               75
liechtenstein                       75
lithuania                           75
luxembourg                          75
macao                               75
madagascar                          75
malawi                              75
malaysia                            75
maldives                            75
mali                                75
malta                               75
marshall islands                    75
mauritania                          75
mauritius                           75
mexico                              75
micronesia (country)                75
moldova                             75
monaco                              75
mongolia                            75
montenegro                          75
morocco                             75
mozambique                          75
myanmar                             75
namibia                             75
nauru                               75
nepal                               75
netherlands                         75
new zealand                         75
nicaragua                           75
niger                               75
nigeria                             75
north korea                         75
north macedonia                     75
norway                              75
oman                                75
pakistan                            75
palau                               75
palestine                           75
panama                              75
papua new guinea                    75
paraguay                            75
peru                                75
philippines                         75
poland                              75
portugal                            75
qatar                               75
romania                             75
russia                              75
rwanda                              75
saint kitts and nevis               75
saint lucia                         75
saint vincent and the grenadines    75
samoa                               75
san marino                          75
sao tome and principe               75
saudi arabia                        75
senegal                             75
serbia                              75
seychelles                          75
sierra leone                        75
singapore                           75
slovakia                            75
slovenia                            75
solomon islands                     75
somalia                             75
south africa                        75
south korea                         75
south sudan                         75
spain                               75
sri lanka                           75
sudan                               75
suriname                            75
sweden                              75
switzerland                         75
syria                               75
taiwan                              75
tajikistan                          75
tanzania                            75
thailand                            75
togo                                75
tonga                               75
trinidad and tobago                 75
tunisia                             75
turkey                              75
turkmenistan                        75
tuvalu                              75
uganda                              75
ukraine                             75
united arab emirates                75
united kingdom                      75
united states                       75
uruguay                             75
uzbekistan                          75
vanuatu                             75
vatican                             75
venezuela                           75
vietnam                             75
yemen                               75
zambia                              75
zimbabwe                            75
------
iso_code
afg    75
alb    75
dza    75
and    75
ago    75
atg    75
arg    75
arm    75
aus    75
aut    75
aze    75
bhs    75
bhr    75
bgd    75
brb    75
blr    75
bel    75
blz    75
ben    75
btn    75
bol    75
bih    75
bwa    75
bra    75
brn    75
bgr    75
bfa    75
bdi    75
khm    75
cmr    75
can    75
cpv    75
caf    75
tcd    75
chl    75
chn    75
col    75
com    75
cog    75
cri    75
civ    75
hrv    75
cub    75
cyp    75
cze    75
cod    75
dnk    75
dji    75
dma    75
dom    75
tls    75
ecu    75
egy    75
slv    75
gnq    75
eri    75
est    75
swz    75
eth    75
fji    75
fin    75
fra    75
gab    75
gmb    75
geo    75
deu    75
gha    75
grc    75
grd    75
gtm    75
gin    75
gnb    75
guy    75
hti    75
hnd    75
hkg    75
hun    75
isl    75
ind    75
idn    75
irn    75
irq    75
irl    75
isr    75
ita    75
jam    75
jpn    75
jor    75
kaz    75
ken    75
kir    75
xkx    75
kwt    75
kgz    75
lao    75
lva    75
lbn    75
lso    75
lbr    75
lby    75
lie    75
ltu    75
lux    75
mac    75
mdg    75
mwi    75
mys    75
mdv    75
mli    75
mlt    75
mhl    75
mrt    75
mus    75
mex    75
fsm    75
mda    75
mco    75
mng    75
mne    75
mar    75
moz    75
mmr    75
nam    75
nru    75
npl    75
nld    75
nzl    75
nic    75
ner    75
nga    75
prk    75
mkd    75
nor    75
omn    75
pak    75
plw    75
pse    75
pan    75
png    75
pry    75
per    75
phl    75
pol    75
prt    75
qat    75
rou    75
rus    75
rwa    75
kna    75
lca    75
vct    75
wsm    75
smr    75
stp    75
sau    75
sen    75
srb    75
syc    75
sle    75
sgp    75
svk    75
svn    75
slb    75
som    75
zaf    75
kor    75
ssd    75
esp    75
lka    75
sdn    75
sur    75
swe    75
che    75
syr    75
twn    75
tjk    75
tza    75
tha    75
tgo    75
ton    75
tto    75
tun    75
tur    75
tkm    75
tuv    75
uga    75
ukr    75
are    75
gbr    75
usa    75
ury    75
uzb    75
vut    75
vat    75
ven    75
vnm    75
yem    75
zmb    75
zwe    75

El dataset no posee ni nombre del país ni código ISO que se encuentre escrito de una manera diferente.

En las columnas numéricas, el año de observación es de tipo int64 lo cual es correcto ya que todos son valores enteros. Las columnas de emisión total y de emisión per capita son valores float, lo cual tambien corresponde a los valores contenidos. No es necesaria transformación de datos.

Trabajamos los valores nulos de emisión total y de emisión per capita. Para esto procederemos primero a identificar los países que no poseen datos registrados y los eliminamos.
Los motivos para ésto son:


1.   Cero información: Al tener un 100% de nulos, no aportan nada a promedios, tendencias o sumatorias. Son "filas vacías" para el análisis de emisiones.
2.   Imputación imposible: No podemos "rellenar" los datos (imputación) basándonos en años anteriores o posteriores porque no existe ningún punto de referencia en todo el histórico de esos países.
3.   Limpieza estadística: Si calculamos, por ejemplo, el "Promedio de emisiones por país", tener estos países en la lista nos obligaría a estar filtrando nulos constantemente para evitar errores o resultados NaN.
4.   Impacto mínimo: Eliminar estos 6 países solo reduce el dataset en 450 filas de un total de casi 15,000 (Aproximadamente 3%), pero mejora significativamente la "salud" de las estadísticas.

In [14]:
# Identificamos países que tienen TODOS sus valores de total_ghg como nulos
paises_sin_datos = df.groupby('country')['total_ghg'].apply(lambda x: x.isnull().all())
nombres_paises_vacios = paises_sin_datos[paises_sin_datos].index.tolist()

print(f"Países eliminados por falta total de datos: {nombres_paises_vacios}")

# Filtramos el DataFrame original para conservar solo los países que SÍ tienen datos
df_limpio = df[~df['country'].isin(nombres_paises_vacios)].copy()

# Verificamos resultados
print(f"Registros originales: {len(df)}")
print(f"Registros tras la limpieza: {len(df_limpio)}")

Países eliminados por falta total de datos: ['kosovo', 'marshall islands', 'monaco', 'palestine', 'san marino', 'vatican']
Registros originales: 14925
Registros tras la limpieza: 14475

Vamos a agregar una columna de cantidad estimada de población, basándonos en los datos de emisión total y emisión per capita.
En este cálculo, como las cantidades en emisión total estan expresadas en millones de toneladas de CO₂ equivalente, el resultado será a su vez en millones de habitantes.

In [16]:
#Creamos la nueva columna "poblacion_en_millones" y hacemos el cálculo
df_limpio['poblacion_en_millones'] = df_limpio['total_ghg'] / df_limpio['ghg_per_capita']

# Verificamos los resultados
print(df_limpio[['country', 'year', 'poblacion_en_millones']].head())

       country  year  poblacion_en_millones
0  afghanistan  1950               7.776180
1  afghanistan  1951               7.879343
2  afghanistan  1952               7.987784
3  afghanistan  1953               8.096703
4  afghanistan  1954               8.207954

# Dataset final

In [17]:
#Exportamos el dataset resultante luego de la limpieza y estandarización
df_limpio.to_csv('dataset_final.csv', index=False)